title:              AzeContent
email:              azecontent@gmail.com
description:        Öz dilimizdə inkişaf edək!
description_en:     Let's improve in our language!

author:             AzeContent
baseurl:            /
baseurl_en:         /en/

url:                "https://azecontent.github.io"

# Social Profiles
twitter_username:  
github_username:   
facebook_username:  AzeContent
instagram_username: AzeContent  
linkedin_username:  AzeContent
youtube_username:  AzeContent

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-172962727-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           100
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
